name: Update feeds
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get up on this
        uses: actions/checkout@v2

      - name: hit it
        run: ./mk/feeds.sh

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'andydecleyre@users.noreply.github.com'
          git add docs/feeds/*
          git commit -am 'Update feeds [Automated]' && git push || true
