name: Update feeds
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get up on this
        uses: actions/checkout@v2

      - name: install sops from GitHub
        run: >-
          wget -P /tmp
          'https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb' &&
          sudo dpkg -i /tmp/sops_*.deb

      - name: configure sops secrets
        run: >-
          mkdir -p "$HOME/.config/sops/age" &&
          echo "$SOPS_SECRET" >"$HOME/.config/sops/age/keys.txt"
        env:
          SOPS_SECRET: ${{ secrets.SOPS_SECRET }}

      - name: hit it
        run: ./mk/feeds.sh

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'andydecleyre@users.noreply.github.com'
          git add docs/feeds/*
          git commit -am 'Update feeds [Automated]' && git push || true
